### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'primary')

### ISSUE THREAD

**Issue by AyushBhardvaj** [ed-roh/mern-social-media#25]
I don't know why I am getting this error. 
Uncaught TypeError: Cannot read properties of undefined (reading 'primary')
    at InputBase.js:66:1
    at transformedStyleArg (createStyled.js:179:1)
    at handleInterpolation (emotion-serialize.browser.esm.js:139:1)
    at serializeStyles (emotion-serialize.browser.esm.js:264:1)
    at emotion-styled-base.browser.esm.js:123:1
    at emotion-element-6a883da9.browser.esm.js:36:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)

There is some problem in InputBase component  
The line of code is  :
 color: (theme.vars || theme).palette.text.primary,

Can anyone explain me the solution?

**Comment by IshaanMehta** [comment]
Were you able to solve the bug? If so please let me know as well

**Comment by Drakar4995** [comment]
@IshaanMehta @AyushBhardvaj  Open the Application, 
![image](https://github.com/ed-roh/mern-social-media/assets/78791354/ff0c706b-1a8a-4593-8919-3d2533f0100f)
delete persist:root, and make sure its not writted 'Ligth' instead of 'Light' you can try to debug like this. 
![image](https://github.com/ed-roh/mern-social-media/assets/78791354/7f71f1f0-81c2-42c9-90d3-6daed27fb0d2)

**Comment by killerTiger10** [comment]
[https://stackoverflow.com/a/69349103/23271799](url)

This solution worked for me.

**Comment by isamnagi** [comment]
my thing was a typo in the const of it
