### ISSUE TITLE
after loggend not acees home page 

### ISSUE THREAD

**Issue by Prasadsolunki** [ed-roh/mern-social-media#44]
My home page doesnt load when I log in. I get this error in the console:

Uncaught TypeError: posts.map is not a function
at PostsWidget (PostsWidget.jsx:41:1)
at renderWithHooks (react-dom.development.js:16305:1)
at mountIndeterminateComponent (react-dom.development.js:20074:1)
at beginWork (react-dom.development.js:21587:1)
at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
at invokeGuardedCallback (react-dom.development.js:4277:1)
at beginWork$1 (react-dom.development.js:27451:1)
at performUnitOfWork (react-dom.development.js:26557:1)
at workLoopSync (react-dom.development.js:26466:1)

**Comment by myyoss** [comment]
Try clear local storage with "clear browsing data". It seems like clearing local storage and session storage in browser application is not good enough..:)

**Comment by Akashkalasagond** [comment]
at my side its just show blank screen with this url: http://localhost:3001/home

**Comment by myyoss** [comment]
Try different browser see if it works
