### ISSUE TITLE
loggin not working

### ISSUE THREAD

**Issue by Vnix0** [ed-roh/mern-social-media#47]
i have this problem can some body help :

Uncaught TypeError: Cannot read properties of undefined (reading '6414c13f932a8a5a100ea491')
    at PostWidget (PostWidget.jsx:30:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
6react-dom.development.js:18687 The above error occurred in the <PostWidget> component:

    at PostWidget (http://localhost:3000/static/js/bundle.js:2707:5)
    at PostsWidget (http://localhost:3000/static/js/bundle.js:2969:5)
    at div
    at http://localhost:3000/static/js/bundle.js:4497:66
    at Box (http://localhost:3000/static/js/bundle.js:21778:72)
    at div
    at http://localhost:3000/static/js/bundle.js:4497:66
    at Box (http://localhost:3000/static/js/bundle.js:21778:72)
    at div
    at http://localhost:3000/static/js/bundle.js:4497:66
    at Box (http://localhost:3000/static/js/bundle.js:21778:72)
    at HomePage (http://localhost:3000/static/js/bundle.js:714:87)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:76956:5)
    at Routes (http://localhost:3000/static/js/bundle.js:77378:5)
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:21055:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:20768:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:21074:5)
    at Router (http://localhost:3000/static/js/bundle.js:77316:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:75648:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:45:72)
    at PersistGate (http://localhost:3000/static/js/bundle.js:83788:5)
    at Provider (http://localhost:3000/static/js/bundle.js:73011:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:12056 Uncaught TypeError: Cannot read properties of undefined (reading '6414c13f932a8a5a100ea491')
    at PostWidget (PostWidget.jsx:30:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js:26096:1)
ff2cfa4e0d9d374d44ac7d58ca956909.jpg:1          Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by myyoss** [comment]
Try clear local storage with "clear browsing data". It seems like clearing local storage and session storage in browser application is not good enough..:)
